<?php

define("ERROR_AUTHROITY_INVALID",ERROR_AUTHROITY | 0x0001);
define("ERROR_AUTHROITY_NOT_FOUND_ROLE",ERROR_AUTHROITY | 0x0002);

define("ERROR_AUTHROITY_ROLE_EXISTS",ERROR_AUTHROITY | 0x0003);
define("ERROR_AUTHROITY_ROLE_NOT_EXISTS",ERROR_AUTHROITY | 0x0004);
define("ERROR_AUTHROITY_ROLE_NAME_IS_NULL",ERROR_AUTHROITY | 0x0005);


define("ERROR_AUTHROITY_ENTITY_ALIAS_IS_NULL",ERROR_AUTHROITY | 0x0006);
define("ERROR_AUTHROITY_ENTITY_EXISTS",ERROR_AUTHROITY | 0x0007);
define("ERROR_AUTHROITY_ENTITY_NOT_EXISTS",ERROR_AUTHROITY | 0x0008);

define("ERROR_AUTHROITY_NOT_FOUND_ROLE_OR_ALIAS",ERROR_AUTHROITY | 0x0009);


/**
 * 权限组件异常
 * @author zhanghailong
 *
 */
class AuthorityException extends Exception{
	
}

?>