<?php

define("ERROR_TRADE_NOT_FOUND_UID",ERROR_TRADE | 0x0001);
define("ERROR_TRADE_NO_PERMISSION",ERROR_TRADE | 0x0002);
define("ERROR_TRADE_STATUS_UNAVIALABLE",ERROR_TRADE | 0x0003);
define("ERROR_TRADE_NOT_FOUND",ERROR_TRADE | 0x0004);
define("ERROR_TRADE_REFUND_PRICE_OUT",ERROR_TRADE | 0x0005);

class TradeException extends Exception{
	
}

?>