<?php

define("ERROR_USER_AUTH_LOGINNAME_OR_PASSWORD",ERROR_ACCOUNT | 0x0001);
define("ERROR_USER_LOGIN_TIMEOUT", ERROR_ACCOUNT | 0x0002);

define("ERROR_USER_EMAIL_EXISTS",ERROR_ACCOUNT | 0x0003);
define("ERROR_USER_EMAIL_FORMAT_ERROR",ERROR_ACCOUNT | 0x0004);

define("ERROR_USER_NOT_FOUND",ERROR_ACCOUNT | 0x0005);
define("ERROR_USER_VERIFY",ERROR_ACCOUNT | 0x0006);

define("ERROR_USER_IS_DISABLED",ERROR_ACCOUNT | 0x0007);

define("ERROR_USER_ACCOUNT_EXISTS",ERROR_ACCOUNT | 0x0008);
define("ERROR_USER_NICK_EXISTS",ERROR_ACCOUNT | 0x0009);
define("ERROR_USER_NOT_FOUND_ACCOUNT",ERROR_ACCOUNT | 0x000A);
define("ERROR_USER_REPEAT_TEL",ERROR_ACCOUNT | 0x000B);

class AccountException extends Exception{
	
}

?>