<?php

define("ERROR_GOODS_NOT_SUPPORT_ITEM_URL",ERROR_GOODS | 0x0001);
define("ERROR_GOODS_ITEM_URL_HTTP",ERROR_GOODS | 0x0002);
define("ERROR_GOODS_ITEM_XSLT",ERROR_GOODS | 0x0003);
define("ERROR_GOODS_IMPORT_NOT_FOUND",ERROR_GOODS | 0x0004);

define("ERROR_GOODS_IMAGE_NOT_FOUND",ERROR_GOODS | 0x0005);
define("ERROR_GOODS_URL_NOT_FOUND",ERROR_GOODS | 0x0006);

class GoodsException extends Exception{
	
}

?>